from src.app.exceptions.user_error import UserError


class ValidationError(UserError):
    pass
